start-at-login = true

[mode.main.binding]

alt-shift-1 = 'workspace 1'
alt-shift-2 = 'workspace 2'
alt-shift-3 = 'workspace 3'
alt-shift-4 = 'workspace 4'
alt-shift-5 = 'workspace 5'

ctrl-alt-1 = 'move-node-to-workspace 1'
ctrl-alt-2 = 'move-node-to-workspace 2'
ctrl-alt-3 = 'move-node-to-workspace 3'
ctrl-alt-4 = 'move-node-to-workspace 4'
ctrl-alt-5 = 'move-node-to-workspace 5'

[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'info.sioyek.sioyek'
run = 'layout floating'
