set -g default-command /usr/bin/fish

# history
set-option -g history-limit 100000

# terminal
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",alacritty:Tc"
set -ga terminal-overrides ",xterm*:smcup@:rmcup@"

# prefix
unbind C-b
set -g prefix C-l
bind-key -n C-l send-prefix

# responsiveness
set -s escape-time 0
set -g repeat-time 250

# reload config
bind r source-file ~/.tmux.conf \; display-message "config reloaded"

# titles
set -g set-titles on
set -g set-titles-string "#T"

# indexing
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# disable bell
set -g bell-action none
set -g visual-bell off

# vi mode
set -g mode-keys vi
set -g mouse on

# paste from system clipboard with Ctrl+V (no shift)
bind -n C-v run "tmux set-buffer -- \"$(xclip -o -selection clipboard)\"; tmux paste-buffer"

# pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# copy mode
bind y copy-mode

set -g set-clipboard on

# copy to system clipboard (xclip for X11)
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -se clipboard -i"
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -se clipboard -i"

# pipe selection to the system clipboard
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -se clipboard -i"
bind-key -T copy-mode    MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -se clipboard -i"

# open new windows and split panes in current directory
bind c new-window -c "#{pane_current_path}"
bind / split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# resize panes
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Base16 Gruvbox Dark, Hard

# Status bar
set-option -g status-style "fg=#bdae93,bg=#3c3836"

# Window titles
set-window-option -g window-status-style "fg=#bdae93,bg=default"
set-window-option -g window-status-current-style "fg=#fabd2f,bg=default"

# Pane borders
set-option -g pane-border-style "fg=#3c3836"
set-option -g pane-active-border-style "fg=#504945"

# Message text
set-option -g message-style "fg=#d5c4a1,bg=#3c3836"

# Pane numbers
set-option -g display-panes-active-colour "#b8bb26"
set-option -g display-panes-colour "#fabd2f"

# Clock
set-window-option -g clock-mode-colour "#b8bb26"

# Copy mode
set-window-option -g mode-style "fg=#bdae93,bg=#504945"

# Bell
set-window-option -g window-status-bell-style "fg=#3c3836,bg=#fb4934"
