-- Static colorscheme: gruvbuddy (resolved from colorbuddy)
-- No colorbuddy dependency - all colors are hardcoded hex values.
-- Generated from the colorbuddy-based gruvbuddy theme.
-- "no italics for comments" applied.
-- All purples → white, all bolds removed.

vim.g.colors_name = "gruvbuddy-static"

local hi = function(name, opts) vim.api.nvim_set_hl(0, name, opts) end

hi("@boolean", { fg = "#de935f" })
hi("@character.special", { fg = "#cc6666" })
hi("@constant", { fg = "#de935f" })
hi("@function", { fg = "#f8fe7a" })
hi("@function.bracket", { fg = "#e0e0e0", bg = "#111111" })
hi("@function.call.lua", { fg = "#5f89ad" })
hi("@keyword", { fg = "#e0e0e0" })
hi("@keyword.faded", { fg = "#666d78" })
hi("@label", { fg = "#f8fe7a" })
hi("@markup.heading.1.delimiter.vimdoc", { fg = "#111111", bg = "#111111", sp = "#e0e0e0" })
hi("@markup.heading.2.delimiter.vimdoc", { fg = "#111111", bg = "#111111", sp = "#e0e0e0", underline = true })
hi("@markup.italic", { italic = true })
hi("@markup.strikethrough", { strikethrough = true })
hi("@markup.strong", {})
hi("@markup.underline", { underline = true })
hi("@module", { fg = "#e0e0e0" })
hi("@normal", { fg = "#e0e0e0", bg = "#111111" })
hi("@number", { fg = "#cc6666" })
hi("@property", { fg = "#81a2be" })
hi("@tag.attribute.html", { fg = "#e0e0e0" })
hi("@tag.delimiter.html", { fg = "#a3bbcf" })
hi("@type", { fg = "#e0e0e0" })
hi("@type.builtin", { fg = "#e0e0e0" })
hi("@variable", { fg = "#e0e0e0" })
hi("@variable.builtin", { fg = "#e0e0e0", bg = "#111111" })
hi("Added", { fg = "#b3f6c0" })
hi("Boolean", { fg = "#de935f" })
hi("Changed", { fg = "#8cf8f7" })
hi("Character", { fg = "#cc6666" })
hi("ColorColumn", { bg = "#4f5258" })
hi("Comment", { fg = "#b0b1b0" })
hi("Conceal", { fg = "#111111", bg = "#4e545d" })
hi("Conditional", { fg = "#e0e0e0" })
hi("Constant", { fg = "#de935f" })
hi("CurSearch", { fg = "#07080d", bg = "#fce094" })
hi("Cursor", { fg = "#111111", bg = "#e0e0e0" })
hi("CursorColumn", { bg = "#2c2e33" })
hi("CursorLine", { bg = "#2b2b2b" })
hi("CursorLineNr", {})
hi("Define", { fg = "#8abeb7" })
hi("Delimiter", { fg = "#e0e2ea" })
hi("DiagnosticDeprecated", { sp = "#ffc0b9", strikethrough = true })
hi("DiagnosticError", { fg = "#cc6666" })
hi("DiagnosticHint", { fg = "#a6dbff" })
hi("DiagnosticInfo", { fg = "#8cf8f7" })
hi("DiagnosticOk", { fg = "#b3f6c0" })
hi("DiagnosticUnderlineError", { sp = "#ffc0b9", underline = true })
hi("DiagnosticUnderlineHint", { sp = "#a6dbff", underline = true })
hi("DiagnosticUnderlineInfo", { sp = "#8cf8f7", underline = true })
hi("DiagnosticUnderlineOk", { sp = "#b3f6c0", underline = true })
hi("DiagnosticUnderlineWarn", { sp = "#fce094", underline = true })
hi("DiagnosticWarn", { fg = "#fce094" })
hi("DiffAdd", { bg = "#33423e" })
hi("DiffChange", { bg = "#33423e" })
hi("DiffDelete", { fg = "#3a414c", bg = "#24282f" })
hi("DiffText", { bg = "#3e4a47" })
hi("Directory", { fg = "#e7b089" })
hi("EndOfBuffer", { fg = "#969896" })
hi("Error", { fg = "#d98c8c" })
hi("ErrorMsg", { fg = "#ffc0b9" })
hi("Float", { fg = "#cc6666" })
hi("FloatBorder", { fg = "#2b2b2b", bg = "#000000" })
hi("FloatShadow", { bg = "#4f5258", blend = 80 })
hi("FloatShadowThrough", { bg = "#4f5258", blend = 100 })
hi("Folded", { fg = "#7c7f7c", bg = "#4e545d" })
hi("Function", { fg = "#f8fe7a" })
hi("Identifier", { fg = "#e0e0e0" })
hi("Include", { fg = "#8abeb7" })
hi("Keyword", { fg = "#e0e0e0" })
hi("Label", { fg = "#f8fe7a" })
hi("LineNr", { fg = "#282a2e", bg = "#111111" })
hi("LspReferenceRead", { bg = "#2b2b2b" })
hi("LspReferenceWrite", { bg = "#2b2b2b" })
hi("MatchParen", { fg = "#8abeb7" })
hi("ModeMsg", { fg = "#b3f6c0" })
hi("MoreMsg", { fg = "#8cf8f7" })
hi("NonText", { fg = "#4e545d" })
hi("Normal", { fg = "#e0e0e0", bg = "#111111" })
hi("NormalFloat", { fg = "#fafafa", bg = "#000000" })
hi("Number", { fg = "#cc6666" })
hi("NvimInternalError", { fg = "#ff0000", bg = "#ff0000" })
hi("OkMsg", { fg = "#b3f6c0" })
hi("Operator", { fg = "#e6b3b3" })
hi("Pmenu", { fg = "#b4b7b4", bg = "#373b41" })
hi("PmenuMatch", {})
hi("PmenuMatchSel", {})
hi("PmenuSbar", { bg = "#111111" })
hi("PmenuSel", { fg = "#111111", bg = "#fbfead" })
hi("PmenuThumb", { bg = "#b4b7b4" })
hi("PreProc", { fg = "#f8fe7a" })
hi("Question", { fg = "#8cf8f7" })
hi("QuickFixLine", { fg = "#8cf8f7" })
hi("RedrawDebugClear", { bg = "#6b5300" })
hi("RedrawDebugComposed", { bg = "#005523" })
hi("RedrawDebugNormal", { reverse = true })
hi("RedrawDebugRecompose", { bg = "#590008" })
hi("Removed", { fg = "#ffc0b9" })
hi("Repeat", { fg = "#cc6666" })
hi("Search", { fg = "#282a2e", bg = "#f8fe7a" })
hi("SignColumn", { fg = "#404349", bg = "#111111" })
hi("Special", { fg = "#e0e0e0" })
hi("SpecialChar", { fg = "#a3685a" })
hi("SpellBad", { sp = "#ffc0b9", undercurl = true })
hi("SpellCap", { sp = "#fce094", undercurl = true })
hi("SpellLocal", { sp = "#b3f6c0", undercurl = true })
hi("SpellRare", { sp = "#8cf8f7", undercurl = true })
hi("Statement", { fg = "#bf4040" })
hi("StatusLine", { fg = "#373b41", bg = "#81a2be" })
hi("StatusLineNC", { fg = "#969896", bg = "#404349" })
hi("StorageClass", { fg = "#f8fe7a" })
hi("String", { fg = "#99cc99" })
hi("Structure", { fg = "#e0e0e0" })
hi("TabLine", { fg = "#5f89ad", bg = "#282a2e" })
hi("TabLineFill", { fg = "#ebdbb2", bg = "#969896" })
hi("TabLineSel", { fg = "#ffffff", bg = "#282a2e" })
hi("Tag", { fg = "#f8fe7a" })
hi("TermCursor", { reverse = true })
hi("Title", { fg = "#e0e2ea" })
hi("Todo", { fg = "#f8fe7a" })
hi("Type", { fg = "#e0e0e0" })
hi("Typedef", { fg = "#f8fe7a" })
hi("Underlined", { underline = true })
hi("Visual", { bg = "#5f89ad" })
hi("WarningMsg", { fg = "#fce094" })
hi("Whitespace", { fg = "#e0e0e0" })
hi("WinBar", { fg = "#9b9ea4", bg = "#07080d" })
hi("WinBarNC", { fg = "#9b9ea4", bg = "#07080d" })
hi("commandmode", { fg = "#ffffff", bg = "#99cc99" })
hi("diffadded", { fg = "#99cc99" })
hi("diffremoved", { fg = "#cc6666" })
hi("gitdiff", { fg = "#c7c7c7" })
hi("helpdoc", { fg = "#ffffff", bg = "#698b69" })
hi("helpignore", { fg = "#99cc99" })
hi("htmlh1", { fg = "#81a2be" })
hi("insertmode", { fg = "#ffffff", bg = "#f8fe7a" })
hi("invnormal", { fg = "#111111", bg = "#c5c8c6" })
hi("lCursor", { fg = "#111111", bg = "#e0e0e0" })
hi("markdownh1", { fg = "#81a2be" })
hi("markdownh2", { fg = "#a3bbcf" })
hi("markdownh3", { fg = "#c4d4e1" })
hi("normalmode", { fg = "#ffffff", bg = "#cc6666" })
hi("qffilename", { fg = "#f8fe7a" })
hi("replacemode", { fg = "#ffffff", bg = "#f8fe7a", underline = true })
hi("telescopematching", { fg = "#e89155" })
hi("terminalmode", { fg = "#ffffff", bg = "#698b69" })
hi("user1", { fg = "#ffffff", bg = "#f8fe7a" })
hi("user2", { fg = "#ffffff", bg = "#cc6666" })
hi("user3", { fg = "#ffffff", bg = "#99cc99" })
hi("variable", { fg = "#e0e0e0" })
hi("visuallinemode", { bg = "#5f89ad" })
hi("visualmode", { bg = "#5f89ad" })
