vim.g.colors_name = "void"

local bg = "#000000"
local fg = "#cccccc"
local selection = "#0000ff"
local comments = "#6b8faf"
local strings = "#707070"
local keywords = "#ffffff"
local functions = "#e8e8e8"
local methods = "#b8b8b8"
local types = "#a0a0a0"
local variables = "#888888"
local constants = "#888888"
local builtin = "#a0a0a0"
local error = "#ff4444"
local warning = "#cccccc"
local highlight_line = "#1a1a1a"
local line_fg = "#4d4d4d"

local hl = vim.api.nvim_set_hl

-- Base
hl(0, "Normal", { fg = fg, bg = bg })
hl(0, "NormalFloat", { fg = fg, bg = bg })
hl(0, "NormalSB", { fg = fg, bg = bg })
hl(0, "Cursor", { fg = bg, bg = "#ffffff" })
hl(0, "CursorLine", { bg = highlight_line })
hl(0, "CursorLineNr", { fg = "#ffffff", bg = highlight_line })
hl(0, "CursorColumn", { bg = highlight_line })
hl(0, "ColorColumn", { bg = "#1a1a1a" })
hl(0, "Conceal", { fg = strings })
hl(0, "DiffAdd", { fg = "#ffffff", bg = "#1a3a1a" })
hl(0, "DiffChange", { bg = "#1a1a2a" })
hl(0, "DiffDelete", { fg = error, bg = "#3a1a1a" })
hl(0, "DiffText", { bg = "#2a2a4a" })
hl(0, "Directory", { fg = "#ffffff", bold = true })
hl(0, "EndOfBuffer", { fg = bg })
hl(0, "ErrorMsg", { fg = error, bold = true })
hl(0, "FloatBorder", { fg = "#ffffff", bg = bg })
hl(0, "FloatTitle", { fg = "#ffffff", bold = true })
hl(0, "Folded", { fg = line_fg, bg = bg })
hl(0, "FoldColumn", { fg = line_fg, bg = bg })
hl(0, "IncSearch", { fg = bg, bg = "#ffffff" })
hl(0, "LineNr", { fg = line_fg, bg = bg })
hl(0, "MatchParen", { fg = "#ffffff", bold = true, underline = true })
hl(0, "ModeMsg", { fg = fg })
hl(0, "MoreMsg", { fg = fg })
hl(0, "NonText", { fg = line_fg })
hl(0, "Pmenu", { fg = fg, bg = "#1a1a1a" })
hl(0, "PmenuSel", { fg = "#ffffff", bg = selection })
hl(0, "PmenuSbar", { bg = "#1a1a1a" })
hl(0, "PmenuThumb", { bg = line_fg })
hl(0, "Question", { fg = keywords })
hl(0, "QuickFixLine", { bg = highlight_line })
hl(0, "Search", { fg = bg, bg = "#ffffff" })
hl(0, "SignColumn", { bg = bg })
hl(0, "SignColumnSB", { bg = bg })
hl(0, "SpecialKey", { fg = line_fg })
hl(0, "SpellBad", { sp = error, undercurl = true })
hl(0, "SpellCap", { sp = warning, undercurl = true })
hl(0, "SpellLocal", { sp = strings, undercurl = true })
hl(0, "SpellRare", { sp = comments, undercurl = true })
hl(0, "StatusLine", { fg = bg, bg = "#d4d4d4" })
hl(0, "StatusLineNC", { fg = "#808080", bg = "#1a1a1a" })
hl(0, "TabLine", { fg = fg, bg = bg })
hl(0, "TabLineFill", { bg = bg })
hl(0, "TabLineSel", { fg = bg, bg = "#ffffff" })
hl(0, "Title", { fg = "#ffffff", bold = true })
hl(0, "Visual", { bg = selection })
hl(0, "VisualNOS", { bg = selection })
hl(0, "WarningMsg", { fg = warning, bold = true })
hl(0, "Whitespace", { fg = "#1a1a1a" })
hl(0, "WinSeparator", { fg = line_fg, bg = bg })
hl(0, "WinBar", { fg = fg, bg = bg })
hl(0, "WinBarNC", { fg = line_fg, bg = bg })
hl(0, "CurSearch", { link = "IncSearch" })

-- Syntax
hl(0, "@comment", { fg = comments, italic = true })
hl(0, "@comment.error", { fg = error })
hl(0, "@comment.warning", { fg = warning })
hl(0, "@comment.todo", { fg = keywords })
hl(0, "@constant", { fg = constants })
hl(0, "@constant.builtin", { fg = constants })
hl(0, "@constant.macro", { fg = constants })
hl(0, "@constructor", { fg = types })
hl(0, "@define", { fg = constants })
hl(0, "@function", { fg = functions, bold = true })
hl(0, "@function.builtin", { fg = functions, bold = true })
hl(0, "@function.call", { fg = functions, bold = true })
hl(0, "@function.macro", { fg = functions })
hl(0, "@function.method", { fg = methods })
hl(0, "@function.method.call", { fg = methods })
hl(0, "@include", { fg = keywords })
hl(0, "@keyword", { fg = keywords, bold = true })
hl(0, "@keyword.conditional", { fg = keywords, bold = true })
hl(0, "@keyword.coroutine", { fg = keywords, bold = true })
hl(0, "@keyword.debug", { fg = keywords, bold = true })
hl(0, "@keyword.directive", { fg = keywords, bold = true })
hl(0, "@keyword.directive.define", { fg = keywords, bold = true })
hl(0, "@keyword.exception", { fg = keywords, bold = true })
hl(0, "@keyword.function", { fg = keywords, bold = true })
hl(0, "@keyword.import", { fg = keywords, bold = true })
hl(0, "@keyword.operator", { fg = keywords, bold = true })
hl(0, "@keyword.repeat", { fg = keywords, bold = true })
hl(0, "@keyword.return", { fg = keywords, bold = true })
hl(0, "@keyword.storage", { fg = keywords, bold = true })
hl(0, "@label", { fg = keywords })
hl(0, "@markup.heading", { fg = "#ffffff", bold = true })
hl(0, "@markup.italic", { italic = true })
hl(0, "@markup.link", { fg = comments, underline = true })
hl(0, "@markup.link.url", { fg = comments, underline = true })
hl(0, "@markup.list", { fg = keywords })
hl(0, "@markup.quote", { fg = strings })
hl(0, "@markup.raw", { fg = strings })
hl(0, "@markup.strikethrough", { strikethrough = true })
hl(0, "@markup.strong", { bold = true })
hl(0, "@markup.underline", { underline = true })
hl(0, "@module", { fg = types })
hl(0, "@namespace", { fg = types })
hl(0, "@none", {})
hl(0, "@number", { fg = constants })
hl(0, "@number.float", { fg = constants })
hl(0, "@operator", { fg = keywords })
hl(0, "@parameter", { fg = variables })
hl(0, "@parameter.reference", { fg = variables })
hl(0, "@property", { fg = variables })
hl(0, "@punctuation.delimiter", { fg = types })
hl(0, "@punctuation.bracket", { fg = types })
hl(0, "@punctuation.special", { fg = types })
hl(0, "@string", { fg = strings, italic = true })
hl(0, "@string.documentation", { fg = strings, italic = true })
hl(0, "@string.escape", { fg = constants })
hl(0, "@string.regexp", { fg = strings, italic = true })
hl(0, "@string.special", { fg = strings, italic = true })
hl(0, "@string.special.symbol", { fg = strings, italic = true })
hl(0, "@tag", { fg = keywords, bold = true })
hl(0, "@tag.attribute", { fg = variables })
hl(0, "@tag.delimiter", { fg = types })
hl(0, "@type", { fg = types })
hl(0, "@type.builtin", { fg = types })
hl(0, "@type.definition", { fg = types })
hl(0, "@type.qualifier", { fg = types })
hl(0, "@variable", { fg = variables })
hl(0, "@variable.builtin", { fg = variables })
hl(0, "@variable.member", { fg = variables })
hl(0, "@variable.parameter", { fg = variables })
hl(0, "@variable.parameter.builtin", { fg = variables })

-- LSP / Diagnostics
hl(0, "DiagnosticError", { fg = error })
hl(0, "DiagnosticWarn", { fg = warning })
hl(0, "DiagnosticInfo", { fg = comments })
hl(0, "DiagnosticHint", { fg = comments })
hl(0, "DiagnosticOk", { fg = strings })
hl(0, "DiagnosticUnderlineError", { sp = error, undercurl = true })
hl(0, "DiagnosticUnderlineWarn", { sp = warning, undercurl = true })
hl(0, "DiagnosticUnderlineInfo", { sp = comments, undercurl = true })
hl(0, "DiagnosticUnderlineHint", { sp = comments, undercurl = true })
hl(0, "DiagnosticUnnecessary", { fg = line_fg })
hl(0, "DiagnosticSignError", { fg = error })
hl(0, "DiagnosticSignWarn", { fg = warning })
hl(0, "DiagnosticSignInfo", { fg = comments })
hl(0, "DiagnosticSignHint", { fg = comments })
hl(0, "DiagnosticFloatingError", { fg = error })
hl(0, "DiagnosticFloatingWarn", { fg = warning })
hl(0, "DiagnosticFloatingInfo", { fg = comments })
hl(0, "DiagnosticFloatingHint", { fg = comments })
hl(0, "DiagnosticVirtualTextError", { fg = error })
hl(0, "DiagnosticVirtualTextWarn", { fg = warning })
hl(0, "DiagnosticVirtualTextInfo", { fg = comments })
hl(0, "DiagnosticVirtualTextHint", { fg = comments })
hl(0, "LspReferenceText", { bg = highlight_line })
hl(0, "LspReferenceRead", { bg = highlight_line })
hl(0, "LspReferenceWrite", { bg = highlight_line })
hl(0, "LspSignatureActiveParameter", { fg = "#ffffff", bold = true })
hl(0, "LspInlayHint", { fg = line_fg, bg = "#0d0d0d" })

-- fzf-lua
hl(0, "FzfLuaNormal", { fg = fg, bg = bg })
hl(0, "FzfLuaBorder", { fg = "#ffffff", bg = bg })
hl(0, "FzfLuaTitle", { fg = "#ffffff", bold = true })
hl(0, "FzfLuaCursor", { fg = bg, bg = "#ffffff" })
hl(0, "FzfLuaCursorLine", { bg = highlight_line })
hl(0, "FzfLuaCursorLineNr", { fg = "#ffffff" })
hl(0, "FzfLuaHelpNormal", { fg = fg, bg = bg })
hl(0, "FzfLuaHeaderBind", { fg = keywords })
hl(0, "FzfLuaHeaderText", { fg = fg })
hl(0, "FzfLuaBufName", { fg = keywords })
hl(0, "FzfLuaBufNr", { fg = strings })
hl(0, "FzfLuaLineNr", { fg = line_fg })
hl(0, "FzfLuaPath", { fg = strings })
hl(0, "FzfLuaPreviewTitle", { fg = comments })

-- gitsigns
hl(0, "GitSignsAdd", { fg = "#ffffff" })
hl(0, "GitSignsChange", { fg = comments })
hl(0, "GitSignsDelete", { fg = error })
hl(0, "GitSignsAddLn", { bg = "#1a3a1a" })
hl(0, "GitSignsChangeLn", { bg = "#1a1a2a" })
hl(0, "GitSignsDeleteLn", { bg = "#3a1a1a" })
hl(0, "GitSignsAddNr", { fg = "#ffffff" })
hl(0, "GitSignsChangeNr", { fg = comments })
hl(0, "GitSignsDeleteNr", { fg = error })

-- harpoon
hl(0, "HarpoonWindow", { fg = fg, bg = bg })
hl(0, "HarpoonBorder", { fg = "#ffffff", bg = bg })

-- oil
hl(0, "OilDir", { fg = "#ffffff", bold = true })
hl(0, "OilFile", { fg = fg })

-- todo-comments
hl(0, "TodoFgFIXME", { fg = error, bold = true })
hl(0, "TodoFgTODO", { fg = keywords, bold = true })
hl(0, "TodoFgNOTE", { fg = comments, bold = true })
hl(0, "TodoFgHACK", { fg = warning, bold = true })
hl(0, "TodoFgWARN", { fg = warning, bold = true })
hl(0, "TodoFgPERF", { fg = variables, bold = true })
hl(0, "TodoFgTEST", { fg = strings, bold = true })
hl(0, "TodoBgFIXME", { bg = error })
hl(0, "TodoBgTODO", { bg = keywords })
hl(0, "TodoBgNOTE", { bg = comments })
hl(0, "TodoBgHACK", { bg = warning })
hl(0, "TodoSignFIXME", { fg = error, bold = true })
hl(0, "TodoSignTODO", { fg = keywords, bold = true })
hl(0, "TodoSignNOTE", { fg = comments, bold = true })
hl(0, "TodoSignHACK", { fg = warning, bold = true })

-- which-key
hl(0, "WhichKey", { fg = keywords, bold = true })
hl(0, "WhichKeyGroup", { fg = functions })
hl(0, "WhichKeyDesc", { fg = fg })
hl(0, "WhichKeySeparator", { fg = strings })
hl(0, "WhichKeyFloat", { bg = bg })
hl(0, "WhichKeyBorder", { fg = "#ffffff", bg = bg })
hl(0, "WhichKeyTitle", { fg = "#ffffff", bold = true })
