;;; mason-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from mason.el

(autoload 'mason-doctor "mason" "\
Validate external program requirements." t)
(autoload 'mason-update-registry "mason" "\
Refresh the mason registry then call CALLBACK.

(fn &optional CALLBACK)" t)
(autoload 'mason-ensure "mason" "\
Ensure Mason is setup.
Call CALLBACK function after setup succeeded or if it already been setup before.

See `mason-setup' for the macro version of this function.

(fn &optional CALLBACK)")
(autoload 'mason-setup "mason" "\
Setup Mason, then run BODY after it succeeded.
See `mason-ensure' for the function version of this macro.

(fn &rest BODY)" nil t)
(function-put 'mason-setup 'lisp-indent-function 'defun)
(autoload 'mason-installed-p "mason" "\
Checks if PACKAGE is already installed.

(fn PACKAGE)")
(autoload 'mason-install "mason" "\
Install a Mason PACKAGE.
If FORCE non nil delete existing installation, if exists.
If INTERACTIVE, ask for PACKAGE and FORCE.

CALLBACK is a function that will be called with one argument,
indicating the package success to install.

(fn PACKAGE &optional FORCE INTERACTIVE CALLBACK)" t)
(autoload 'mason-uninstall "mason" "\
Uninstall a Mason PACKAGE.
If INTERACTIVE, ask for PACKAGE.

CALLBACK is a function that will be called with one argument,
indicating the package success to uninstall.

(fn PACKAGE &optional INTERACTIVE CALLBACK)" t)
(autoload 'mason-update "mason" "\
Update a Mason PACKAGE.
If INTERACTIVE, ask for PACKAGE.

CALLBACK is a function that will be called with one argument,
indicating the package success to update.

(fn PACKAGE &optional INTERACTIVE CALLBACK)" t)
(autoload 'mason-update-all "mason" "\
Update all Mason packages.
CALLBACK is a function that will be called with one argument,
indicating a package success to update.

(fn &optional CALLBACK)" t)
(register-definition-prefixes "mason" '("mason-"))


;;; Generated autoloads from mason-basic.el

(autoload 'mason-log "mason-basic" "\
Show the Mason Log buffer." t)
(register-definition-prefixes "mason-basic" '("mason-"))


;;; Generated autoloads from mason-info.el

(autoload 'mason-info "mason-info" "\
Visit Mason info file for PACKAGE.
If INTERACTIVE, ask for PACKAGE.

(fn PACKAGE &optional INTERACTIVE)" t)
(register-definition-prefixes "mason-info" '("mason-"))


;;; Generated autoloads from mason-manager.el

(autoload 'mason-manager "mason-manager" "\
Open mason package manager." t)
(register-definition-prefixes "mason-manager" '("mason-manager-"))

;;; End of scraped data

(provide 'mason-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; mason-autoloads.el ends here
