# history
set-option -g history-limit 100000

# terminal
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",alacritty:Tc"
set -ga terminal-overrides ",xterm*:smcup@:rmcup@"

# prefix
unbind C-b
set -g prefix C-l
bind-key -n C-l send-prefix

# responsiveness
set -s escape-time 0
set -g repeat-time 250

# reload config
bind r source-file ~/.tmux.conf ; display-message "config reloaded"

# titles
set -g set-titles on
set -g set-titles-string "#T"

# indexing
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# vi mode
set -g mode-keys vi
set -g mouse on

# pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# copy mode
bind y copy-mode
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "pbcopy"

# split panes in current directory
bind / split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# resize panes
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Carbonfox (Nightfox family)
# Scheme author: EdenEast (https://github.com/EdenEast/nightfox.nvim)
# Ported from Base16 Gruvbox dark, hard

# status bar position
set -g status-position bottom

# status bar
set -g status-style "fg=#b1b1b1,bg=#161616"

# window list
setw -g window-status-style "fg=#8c8c8c,bg=#161616"
setw -g window-status-format " #I:#W "

# active window
setw -g window-status-current-style "fg=#ff7eb6,bg=#161616"
setw -g window-status-current-format " #I:#W* "

# pane borders
set -g pane-border-style "fg=#393939"
set -g pane-active-border-style "fg=#ff7eb6"

# copy mode
setw -g mode-style "fg=#f2f4f8,bg=#282828"

# messages
set -g message-style "fg=#dfdfe5,bg=#161616"

# pane number display
set -g display-panes-colour "#ff7eb6"
set -g display-panes-active-colour "#25be6a"

# clock
setw -g clock-mode-colour "#25be6a"

# bell
setw -g window-status-bell-style "fg=#161616,bg=#ee5396"

# command prompt
set -g message-command-style "fg=#f2f4f8,bg=#282828"
