# history
set-option -g history-limit 100000

# terminal
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",alacritty:Tc"
set -ga terminal-overrides ",xterm*:smcup@:rmcup@"

# prefix
unbind C-b
set -g prefix C-l
bind-key -n C-l send-prefix

# responsiveness
set -s escape-time 0
set -g repeat-time 250

# reload config
bind r source-file ~/.tmux.conf \; display-message "config reloaded"

# titles
set -g set-titles on
set -g set-titles-string "#T"

# indexing
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# disable bell
set -g bell-action none
set -g visual-bell off

# vi mode
set -g mode-keys vi
set -g mouse on

# paste from system clipboard with Ctrl+V (no shift)
bind -n C-v run "tmux set-buffer -- \"$(xclip -o -selection clipboard)\"; tmux paste-buffer"

# pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# copy mode
bind y copy-mode

set -g set-clipboard on

# copy to system clipboard (xclip for X11)
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -se clipboard -i"
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -se clipboard -i"

# Track mouse release to pipe the selection straight to the system clipboard
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -se clipboard -i"
bind-key -T copy-mode    MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -se clipboard -i"


# open new windows and split panes in current directory
bind c new-window -c "#{pane_current_path}"
bind / split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# resize panes
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
