# history
set-option -g history-limit 100000
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",alacritty:Tc"

# let ghostty handle scrollback (disable alt screen)
set -ga terminal-overrides ',xterm*:smcup@:rmcup@'

# prefix
unbind C-b
set -g prefix C-l
bind-key -n C-l send-prefix
set -s escape-time 0
set -g repeat-time 250

# reload the config
bind r source-file ~/.tmux.conf \; display-message "config reloaded"

# titles
set -g set-titles on
set -g set-titles-string "#T"
set -g base-index 1
set -g pane-base-index 1

#vi mods
set -g mode-keys vi
set -g mouse on
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# mac-os keyboard
bind C-c copy-mode
bind C-v paste-buffer
bind -T copy-mode-vi y     send-keys -X copy-pipe-and-cancel "pbcopy"
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "pbcopy"

# gruvbox styling
set-option -g status-style "fg=#bdae93,bg=#1c1816"
set-window-option -g window-status-style "fg=#bdae93,bg=#1c1816"
set-window-option -g window-status-current-style "fg=#fabd2f,bg=#1c1816"
set-option -g pane-border-style "fg=#3c3836"
set-option -g pane-active-border-style "fg=#504945"
set-option -g message-style "fg=#d5c4a1,bg=#3c3836"
set-option -g display-panes-active-colour "#b8bb26"
set-option -g display-panes-colour "#fabd2f"
set-window-option -g clock-mode-colour "#b8bb26"
set-window-option -g mode-style "fg=#bdae93,bg=#504945"
set-window-option -g window-status-bell-style "fg=#3c3836,bg=#fb4934"

# override status bar content to remove default colors
set-option -g status-left "#[fg=#bdae93,bg=#1c1816] [#S] "
set-option -g status-right "#[fg=#bdae93,bg=#1c1816] %H:%M %d-%b-%y "

# override window status formats (this is key!)
set-window-option -g window-status-format "#[fg=#bdae93,bg=#1c1816] #I:#W#F "
set-window-option -g window-status-current-format "#[fg=#fabd2f,bg=#1c1816,bold] #I:#W#F "

