set -g history-limit 100000
set -g default-terminal "tmux-256color"
set -g terminal-overrides ",alacritty:Tc,xterm*:smcup@:rmcup@" # gettings ghostty to control the scroll

# cntrl + l = prefix
unbind C-b
set -g prefix C-l
bind-key -n C-l send-prefix
set -s escape-time 0
set -g repeat-time 250

# reload the config
bind r source-file ~/.tmux.conf \; display-message "config reloaded"

set -g set-titles on
set -g set-titles-string "#T"
set -g base-index 1
set -g pane-base-index 1

set -g mode-keys vi
set -g mouse on

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind C-c copy-mode
bind C-v paste-buffer
bind -T copy-mode-vi y     send-keys -X copy-pipe-and-cancel "pbcopy"
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "pbcopy"

set -g status-style 'bg=#333333 fg=#5eacd3'

