##### History / Terminal #####
set -g history-limit 100000
set -g default-terminal "tmux-256color"
set -g terminal-overrides ",alacritty:Tc,xterm*:smcup@:rmcup@"

##### Prefix #####
unbind C-b
set -g prefix C-l
bind-key -n C-l send-prefix
set -s escape-time 0
set -g repeat-time 250

##### Titles #####
set -g set-titles on
set -g set-titles-string "#T"
set -g base-index 1
set -g pane-base-index 1

##### Controls #####
set -g mode-keys vi
set -g mouse on

# Vim-style pane movement
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

##### Clipboard / Copy #####
bind C-c copy-mode
bind C-v paste-buffer
bind -T copy-mode-vi y     send-keys -X copy-pipe-and-cancel "pbcopy"
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "pbcopy"

##### Status Bar #####
set -g status-position bottom
set -g status-bg black
set -g status-fg colour141
set -g status-right ''
set -g status-right-length 9

